package com.george_vi.electroenergetics.config;

import com.mojang.logging.LogUtils;
import net.createmod.catnip.config.ConfigBase;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.ModLoadingContext;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.fml.event.config.ModConfigEvent;
import net.neoforged.neoforge.common.ModConfigSpec;
import org.apache.commons.lang3.tuple.Pair;
import org.slf4j.Logger;

import java.util.EnumMap;
import java.util.Map;
import java.util.function.Supplier;

public class CEEConfigs {

    private static final Logger LOGGER = LogUtils.getLogger();

    private static final Map<ModConfig.Type, ConfigBase> CONFIGS = new EnumMap<>(ModConfig.Type.class);

    private static CServer server;
    private static CClient client;

    public static CServer server() {
        return server;
    }

    public static CClient client() {
        return client;
    }

    public static ConfigBase byType(ModConfig.Type type) {
        return CONFIGS.get(type);
    }

    private static <T extends ConfigBase> T register(Supplier<T> factory, ModConfig.Type side) {
        Pair<T, ModConfigSpec> specPair = new ModConfigSpec.Builder().configure(builder -> {
            T config = factory.get();
            config.registerAll(builder);
            return config;
        });

        T config = specPair.getLeft();
        config.specification = specPair.getRight();
        CONFIGS.put(side, config);
        return config;
    }

    public static void register(ModLoadingContext context, ModContainer container) {
        client = register(CClient::new, ModConfig.Type.CLIENT);
        server = register(CServer::new, ModConfig.Type.SERVER);

        for (Map.Entry<ModConfig.Type, ConfigBase> pair : CONFIGS.entrySet())
            container.registerConfig(pair.getKey(), pair.getValue().specification);
    }

    @SubscribeEvent
    public static void onLoad(ModConfigEvent.Loading event) {
        for (ConfigBase config : CONFIGS.values())
            if (config.specification == event.getConfig()
                    .getSpec()) {
                config.onLoad();
                if (config == server)
                    logEffectiveTraction();
            }
    }

    @SubscribeEvent
    public static void onReload(ModConfigEvent.Reloading event) {
        for (ConfigBase config : CONFIGS.values())
            if (config.specification == event.getConfig()
                    .getSpec()) {
                config.onReload();
                if (config == server)
                    logEffectiveTraction();
            }
    }

    /**
     * Print the traction numbers this session will actually use.
     *
     * <p>NeoForge keeps whatever value is already written in the config file when
     * a mod changes a default, so a config generated by an older build silently
     * pins the old figures and the file even shows the new default in its
     * comment next to the old value. That once made a train cap out at 45 m/s
     * while the code said 100, with nothing in the log to hint at why. This
     * makes the effective settings visible in one place, and calls out any key
     * still sitting on a superseded default.
     */
    private static void logEffectiveTraction() {
        CTrains trains = server.trainValues;
        CResistances res = server.resistanceValues;

        float maxSpeed = trains.electricTrainMaxSpeed.getF();
        float perCarriage = trains.electricTrainPowerPerCarriage.getF();
        float accel = trains.electricTrainMaxAcceleration.getF();
        double gamma = res.electricTrainRotatingMassFactor.get();
        double aeroC = res.electricTrainBasicResistanceC.get();

        LOGGER.info(
                "Traction settings: vMax={} m/s, {} W/carriage, aMax={} m/s^2, "
                        + "gamma={}, aeroC={}, mass={} kg/carriage, copper={} ohm/m",
                maxSpeed, perCarriage, accel, gamma, aeroC,
                res.electricTrainMassPerCarriage.get(), res.copperWireResistance.get());

        logBaseSpeed(accel, gamma, res.electricTrainMassPerCarriage.get());

        // Values a build used to ship, now superseded. Left here so an old config
        // announces itself instead of behaving inexplicably.
        warnIfStale("electricTrainMaxSpeed", maxSpeed, 100f);
        warnIfStale("electricTrainPowerPerCarriage", perCarriage, 1_375_000f);
        warnIfStale("electricTrainMaxAcceleration", accel, 2.0f);
        warnIfStale("electricTrainRotatingMassFactor", (float) gamma, 0.06f);
        warnIfStale("electricTrainBasicResistanceC", (float) aeroC, 0.0014f);
    }

    /**
     * Report where the consist leaves the torque-limited region and starts
     * running at full power, for a single carriage.
     *
     * <p>That break point is {@code rating / (mass * (1 + gamma) * aMax)}, and it
     * is the number that decides whether the train feels like it pulls at full
     * power from a standstill or only after a long ramp. It is not obvious from
     * the raw config values, so it is worth stating outright.
     */
    private static void logBaseSpeed(float accel, double gamma, double massPerCarriage) {
        if (!(accel > 0f) || !(massPerCarriage > 0d))
            return;
        float perCarriage = server.trainValues.electricTrainPowerPerCarriage.getF();
        double efficiency = server.resistanceValues.electricTrainDriveEfficiency.get();
        double effort = massPerCarriage * (1d + gamma) * accel;
        if (!(effort > 0d))
            return;
        double baseSpeed = perCarriage * efficiency / effort;
        LOGGER.info("Constant-power region begins at {} Blocks/Second ({} km/h) "
                        + "for a single carriage; below that the motors are torque-limited.",
                String.format("%.1f", baseSpeed), String.format("%.0f", baseSpeed * 3.6));
    }

    private static void warnIfStale(String key, float actual, float current) {
        // Relative tolerance: these are floats compared against doubles that were
        // widened from floats, so an exact == would be fragile.
        float scale = Math.max(Math.abs(current), 1e-6f);
        if (Math.abs(actual - current) <= scale * 1e-4f)
            return;
        LOGGER.warn(
                "Config key '{}' is set to {}, but this version expects {}. "
                        + "An older build wrote that value and NeoForge will not overwrite it; "
                        + "delete the line (or the file) to pick up the new default.",
                key, actual, current);
    }
}
